name: Validate File JSON

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: npm install
      shell: bash
    - name: Validate Files
      run: npm run validate
      shell: bash
